spring:

  application:
    name: vehiforge-ConfigurationService

  datasource:
    url: jdbc:postgresql://${DB_HOST}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: localhost:9095
    consumer-group-id: configuration-service
    consumers:
      config-change:
        name: 'configurator.vehicle-configuration-change'
      part-updated:
        name: 'configurator.part-added-or-updated'

security:
  user-service-url: ${USER_SERVICE_URL}

server:
  address: 0.0.0.0
  port: 8083