apiVersion: apps/v1
kind: Deployment
metadata:
  name: vehiforge-user-service
  labels:
    app: vehiforge-user-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vehiforge-user-service
  template:
    metadata:
      labels:
        app: vehiforge-user-service
    spec:
      containers:
        - name: vehiforge-user-service
          image: shubhamsapkal1/vehiforge-user_service
          ports:
            - containerPort: 8081
          env:
            - name: USER_SERVICE_URL
              value: http://localhost:8081
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: DB_HOST
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: DB_NAME
            - name: TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: TOKEN_SECRET
